# Generated by Django 4.2.4 on 2023-09-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_by',
            new_name='user',
        ),
    ]
